# Generated by Django 5.2 on 2025-05-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('academic_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('vacancy_city', models.CharField(blank=True, max_length=100, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('working_days', models.CharField(blank=True, max_length=100, null=True)),
                ('application_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_date', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
