# Generated by Django 5.2 on 2025-05-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_academic_qualification_alter_job_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
