# Generated by Django 5.2 on 2025-05-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_userrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobuserrelation',
            name='relation',
            field=models.CharField(choices=[('viewed', 'Viewed'), ('bookmark', 'Bookmarked'), ('interview', 'Interview Scheduled'), ('offer', 'Offered'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('liked', 'Liked'), ('applied', 'Applied')], max_length=20),
        ),
    ]
